### ISSUE TITLE
new api

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/multipart-read-stream#6]
Figured this might be easier to read / figure out what's going on:
```js
var multipart = require('multipart-read-stream')
var http = require('http')
var pump = require('pump')

http.createServer(function (req, res) {
  var type = req.headers['content-type']
  var filestream = multipart(type, fileHandler)

  pump(req, filestream, function (err) {
    if (err) (res.statusCode = 400 && res.end('oh no!'))
    res.end()
  })

  function fileHandler (fieldname, file, filename) {
    console.log(`reading file ${filename} from field ${fieldname}`)
    file.pipe(process.stdout)
  }
}).listen(8080)
```
cc/ @davidmarkclements thoughts?

**Comment by davidmarkclements** [comment]
yeah I think it's more expressive in terms of the details... there was something nice about it just taking `req` and doing "magic" .. .but It's better if details are understood... 

I think the first param should be an options object though - 

```js
multipart({type}, handler) 
```

it could also support 'content-type' as well as type, then you can do 

```js
multipart(req.headers, handler) 
```

**Comment by yoshuawuyts** [comment]
oh yeah, I like that hey :sparkles: - nice one!

**Comment by davidmarkclements** [comment]
btw `content-disposition` and `content-transfer-encoding` also have a bearing on how the multipart data is processed by pez

so whether we should.. alias these as well (if we are aliasing content-type -> type) I'm not sure

**Comment by yoshuawuyts** [comment]
oh, I think if we don't alias them it's cool - so just passing `headers` as the first arg works, and if you want to use different values you need to pass the header names as the keys in order to set it (:

**Comment by yoshuawuyts** [comment]
God this [content-transfer-encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) stuff reads like a wizard manual haha
